### ISSUE TITLE
Documentation/pedagogy

### ISSUE THREAD

**Issue by KvalheimRacing** [WAGO/docker-compose-ipk#1]
Hi m8s

In your readme, I think you should at least have one line describing what docker compose is.
I.e.: "Compose is a tool for defining and running multi-container Docker applications."

And then a link to docker-compose documentation etc.

Thanks

**Comment by Helmut-Saal** [comment]
Hello,
I think the user of the Docker-Compose wants to use knows what the tool is for.
This repo is not intended to explain what Docker-Compose is but to provide you with an installation package for our hardware platform.
But thanks for the note.

**Comment by KvalheimRacing** [comment]
> I think the user of the Docker-Compose wants to use knows what the tool is for.
Well I disagree. The thing about open source is that there are a lot of people using stuff they don't know.

> This repo is not intended to explain what Docker-Compose is but to provide you with an installation package for our hardware platform.
You don't really explain what Docker-Compose is with the sentence `Compose is a tool for defining and running multi-container Docker applications.` but you give the reader a little idea about what it is.

Additionally, if the user already know that `Compose is a tool for defining and running multi-container Docker applications.` it's a good thing that it stands there. Reading something familiar which is known is good when combining it with new unfamilliar material. That's the pedagogical aspect I was hinting at.

> But thanks for the note.
No problem, just want to contribute to improving the repo. Currently working on making the [Wago Norge GitHub Organization](https://github.com/wago-norge) site.

Cheers m8
